### ISSUE TITLE
Autoconf dependencies from gettext

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/nuspell#1]
Even though most of gettext has been removed, still the following error occurs:

    autoreconf -vfi
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    ...
    ...
    ...
    m4/iconv.m4:20: AM_ICONV_LINK is expanded from...
    m4/iconv.m4:233: AM_ICONV is expanded from...
    configure.ac:26: the top level
    configure:16487: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    configure:16488: error: possibly undefined macro: AC_LIB_RPATH
    configure:16493: error: possibly undefined macro: AC_LIB_LINKFLAGS_BODY
    configure:16501: error: possibly undefined macro: AC_LIB_APPENDTOVAR
    autoreconf: /usr/bin/autoconf failed with exit status: 1

This can be fixed with `sudo apt-get install gettext` but that means that gettext is still needed. So a better solution for this needs et be found.

**Comment by dimztimz** [comment]
Some macros need to be copied from `/usr/share/aclocal` to our m4 and thats it.

**Comment by dimztimz** [comment]
ICONV is still needed for hunspell executable. Can't remove iconv

**Comment by PanderMusubi** [comment]
Any idea which macros and how to copy them?

**Comment by dimztimz** [comment]
Grepping looks like `lib-link.m4`. That may depend on some others. Copy the macros aside, remove gettext and try first with lib-link.

**Comment by PanderMusubi** [comment]
I needed to copy `lib-ld.m4`, `lib-link.m4` and `lib-prefix.m4` from `/usr/share/aclocal` from package `gettext` to nuspell/m4 in order to get building process going again with having `gettext` installed. These three files have been added to git too now.

**Comment by PanderMusubi** [comment]
@dimztimz Do we need to put a `wget` in place to automatically update these files? You know, in a similar way we get the latest version of libboost.

**Comment by dimztimz** [comment]
No. M4 files just stand there and are rarely updated. And they must exist before calling autoreconf. We use wget only for Catch.

We can have some shell script that would be run manually like once per year but dont see a need for that.

**Comment by PanderMusubi** [comment]
Yes, I mean catch, not boost. I will reopen this issue so we won't forget adding those scripts.

**Comment by PanderMusubi** [comment]
Added a script. Please review it.

**Comment by dimztimz** [comment]
I don't think we needed script. Eventually we will remove the hunspell executable at some point and thus iconv dependency.

**Comment by dimztimz** [comment]
Instead messing with the script, remove it, in the m4/README add which script where it originates from and what is it for.

E.g. these lib-*.m4 originate from [gnulib](http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=tree), if we use gnulib that tool will automatically copy those m4s . So actually the proper way to update that iconv.m4 stuff is by running:

```
gnulib-tool --import iconv
```
And that will add four m4 files and some other stuff. Try that.

I give a try to gnulib tool in the past. Nice tool but don't want to complicate stuff, just manually copy m4s.

**Comment by PanderMusubi** [comment]
Removed the script and moved the documentation to README. If you want to add some more lines, as you described here, feel free to do so.
