### ISSUE TITLE
missing -a parameter

### ISSUE THREAD

**Issue by baarsrj** [hunspell/nuspell#10]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [x ] Change request or feature request
- [ ] Others, questions

# Reporting bugs
The hunspell -a paramter is not in Nuspell; This parameter is used a lot by me, to collect suggestions for (wrong) words, and judging the corrections as well. (they can be added as forbiddenwords when nonsense)

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = | Kubuntu 16      |
| Hunspell version                = |  -     |
| Dictionary,package name,version = |       |
| Command line tool or GUI app    = |   command line    |

## Steps to reproduce
try nuspell -a

## Bugged behavior (output)
ruud@ruud-laptop:~/Bureaublad/nuspell-master$ nuspell -a
Unrecognized option: '-a'
Invalid (combination of) arguments, try 'nuspell --help' for more information
ruud@ruud-laptop:~/Bureaublad/nuspell-master$ hunspell -a 
@(#) International Ispell Version 3.2.06 (but really Hunspell 2.0.0)
duer 
& duer 10 0: deur, dure, dier, duet, der, duwer, deer, duel, duur, perdue

^C
ruud@ruud-laptop:~/Bureaublad/nuspell-master$ nuspell -a
Unrecognized option: '-a'
Invalid (combination of) arguments, try 'nuspell --help' for more information
ruud@ruud-laptop:~/Bureaublad/nuspell-master$ 

## Expected behavior (output)

# Change/feature request
add -a or somthing alike to get suggestions on command line.

# Other issues

**Comment by dimztimz** [comment]
See #9

**Comment by astoff** [comment]
Are there still plans to implement the standard ispell `-a` interface?

**Comment by dimztimz** [comment]
> Are there still plans to implement the standard ispell `-a` interface?

If you want to fund the development, then yes.

Why do you need the `-a` interface?

**Comment by astoff** [comment]
The `-a` interface is useful when a program wants to provide spellchecking without being linked against a spellchecking library. Emacs for example takes such approach.

In general, I guess if someone wanted to provide a third-party nuspell plugin for "random text editor X" there might not be any options other than having some subprocess communicating via a standard interface like `-a`.
