### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by baarsrj** [hunspell/nuspell#12]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [ ] Change request or feature request
- [x] Others, questions

Since I use Hunspell with over 40 languages, I could give it a try to check all collected words for all languages and use -G and -L to list correct and incorrect words with Hunspell as well as Nuspell, and list differences. If this would be of any help, that is.

Apart from the 'to do list', I am also curious about the functionality already implemented.

**Comment by dimztimz** [comment]
See #5 and the repository misc-hunspell
