### ISSUE TITLE
Javascript bindings via webassembly

### ISSUE THREAD

**Issue by kwonoj** [hunspell/nuspell#14]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [x] Change request or feature request
- [x] Others, questions

(Probably more close to `Others` part)

# Other issues

I am aware current development stage is very early and also language bindings are currently targeted post-2 initial MVP stage, but please allow raising questions bit earlier. Feel freely close issue as needed.

I am currently maintaining / using [hunspell-asm](https://github.com/kwonoj/hunspell-asm), javascript bindings to `hunspell` and exposes near 1:1 interfaces to original hunspell's C api (near in terms for exposed interfaces, I omitted lot of interfaces I do not use currently). Basic idea is compile c/cpp code of hunspell via emscripten to compile web assembly binary, and provide glue / interface javascript wrapper to easily access those. 

With new nuspell, when it comes to think of language bindings, how do you think about providing wasm bindings as js binding for official support? There are small handful of macro-defined emscripten specific to bind cpp classes to javascript (https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html), which could be possibly user-land by manually patching main repo code but curious if there's possibility those changes could go upstream and js binding lives as sort of official one instead.

I can definitely try out basic changes / CI setups if needed, I did similar things on hunspell-asm mostly isolated via docker images so could easily run to CI to produce build.

**Comment by dimztimz** [comment]
For now this is out of scope so can't say anything about it. It is planned, but in a future version, to provide bindings with another programming languages. Still, you are free to experiment.

**Comment by kwonoj** [comment]
sounds fair.
