### ISSUE TITLE
Compile error on Windows using Mingw64 and MSYS2

### ISSUE THREAD

**Issue by willbush** [hunspell/nuspell#19]
- [X] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

| key                               | value                |
|-----------------------------------|----------------------|
| OS, distro, version             = | Win 10               |
| nuspell version                 = | latest master branch |

Current latest commit hash:

```bash
$ git rev-parse HEAD
7c075a2d77d3a1783fd52a2f0fe2a6aef4e231d0
```

Here is the build error:

```bash
will@DESKTOP-UCBSDOR MINGW64 ~/Desktop/nuspell/nuspell
$ make
make  all-recursive
make[1]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell'
Making all in src
make[2]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell/src'
Making all in hunspell
make[3]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell/src/hunspell'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src/hunspell'
Making all in parsers
make[3]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell/src/parsers'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src/parsers'
Making all in tools
make[3]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell/src/tools'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/hunspell -I../../src/hunspell -I../ 
../src/parsers  -I/mingw64/include -std=c++14  -g -O2 -MT hunspell.o -MD -MP -MF
.deps/hunspell.Tpo -c -o hunspell.o hunspell.cxx
hunspell.cxx: In function 'char* mymkdtemp(char*)':
hunspell.cxx:649:10: error: 'mkdtemp' was not declared in this scope
   return mkdtemp(templ);
          ^~~~~~~
hunspell.cxx:649:10: note: suggested alternative: 'mktemp'
   return mkdtemp(templ);
          ^~~~~~~
          mktemp
make[3]: *** [Makefile:476: hunspell.o] Error 1
make[3]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src/tools'
make[2]: *** [Makefile:386: all-recursive] Error 1
make[2]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src'
make[1]: *** [Makefile:491: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell'
make: *** [Makefile:400: all] Error 2

will@DESKTOP-UCBSDOR MINGW64 ~/Desktop/nuspell/nuspell
$                                                                       ^
```

## Steps to reproduce

1. Install https://www.msys2.org/ and follow installation steps.

2. Clone latest from master `git clone https://github.com/hunspell/nuspell.git`
   into a folder that doesn't need Admin rights such as your Desktop.

3. Run Msys64 and install `pacman -S base-devel mingw-w64-x86_64-toolchain
   mingw-w64-x86_64-libtool mingw-w64-x86_64-boost`

4. build: 

```bash 
autoreconf -vfi
./configure
make
```

Make should fail with a build error.

**Comment by willbush** [comment]
I'm not sure why `mkdtemp` is not declared in the scope. According to the [man pages](http://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdtemp.htmll) `stdlib.h` should have it. If I change it from `mkdtemp` to `mktemp`, then the build works. However, These functions differ in behavior, so it should take more consideration. I haven't written any C/C++ since college so I'm a little out of my depth in that regard.

**Comment by dimztimz** [comment]
Thank you for the interest in nuspell.

The error is probably on your side, you are not using MSYS2 prompt and not MINGW64 prompt. There are three of them. Maybe try changing that `#ifdef WIN32` to `#ifdef _WIN32`

Various portability issues will be handled before releasing and not now, therefor I will close this. If you are interested, please fix it and send patch, otherwise it is out of scope for me.

**Comment by willbush** [comment]
@dimztimz changing `#ifdef WIN32` to `#ifdef _WIN32` worked.
