### ISSUE TITLE
Boost Locale od OS X does not uses ICU backend

### ISSUE THREAD

**Issue by dimztimz** [hunspell/nuspell#2]
The issues can be of three types (put an X between the brackets):

- [x] Bug reports

# Steps to reproduce

See tests for to_upper and to_title https://travis-ci.org/hunspell/nuspell/builds/332942906

# Possible solutions

1. Configure Boost locale to link with icu4c on OS X.
2. Disable OS X from CI and handle everything at the end. OS X is not a good platform for development, just disturbs. Solve OS X issues at the end.
3. Don't use `boost::locale::to_upper`, `to_title`. Handle them manually like in hunspell v1. Not that big deal.

**Comment by PanderMusubi** [comment]
I'd suggest, for now 2. Then try 1 at a later point in time. If that is impossible, go for 3.

**Comment by dimztimz** [comment]
This is resolved.

Travis OSX is disabled. installing boost with `brew install boost --with-icu4c` will get the wanted effect, but takes maybe 1 hour because it builds from sources. Readme is updated.
