### ISSUE TITLE
Compiling error under MSVC

### ISSUE THREAD

**Issue by LiMinggang** [hunspell/nuspell#20]
The issues can be of three types (put an X between the brackets):

- [x] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = |   Windows 7    |
| Hunspell version                = |       |
| Dictionary,package name,version = |       |
| Command line tool or GUI app    = |    VS 2017 15.4   |

## Bugged behavior (output)
1>------ Build started: Project: Project1, Configuration: Debug Win32 ------
1>affentry.cxx
1>c:\dev\nuspell-master\src\hunspell\hunzip.hxx(70): warning C4251: 'Hunzip::fin': class 'std::basic_ifstream<char,std::char_traits<char>>' needs to have dll-interface to be used by clients of class 'Hunzip'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\iosfwd(608): note: see declaration of 'std::basic_ifstream<char,std::char_traits<char>>'
1>c:\dev\nuspell-master\src\hunspell\hunzip.hxx(72): warning C4251: 'Hunzip::dec': class 'std::vector<bit,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'Hunzip'
1>        with
1>        [
1>            _Ty=bit
1>        ]
1>c:\dev\nuspell-master\src\hunspell\hunzip.hxx(72): note: see declaration of 'std::vector<bit,std::allocator<_Ty>>'
1>        with
1>        [
1>            _Ty=bit
1>        ]
1>c:\dev\nuspell-master\src\hunspell\affentry.hxx(121): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
1>c:\dev\nuspell-master\src\hunspell\affentry.hxx(202): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
1>dictionary.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(230): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(231): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(235): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(233): error C2091: function returns function
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(295): note: see reference to class template instantiation 'nuspell::String_Set<char>' being compiled
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(234): error C2091: function returns function
1>finder.cxx
1>locale_utils.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>c:\dev\nuspell-master\src\nuspell\locale_utils.cxx(31): fatal error C1083: Cannot open include file: 'unicode/uchar.h': No such file or directory
1>main.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(230): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(231): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(235): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(233): error C2091: function returns function
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(295): note: see reference to class template instantiation 'nuspell::String_Set<char>' being compiled
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(234): error C2091: function returns function
1>structures.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(230): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(231): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(235): warning C4068: unknown pragma
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(233): error C2091: function returns function
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(295): note: see reference to class template instantiation 'nuspell::String_Set<char>' being compiled
1>c:\dev\nuspell-master\src\nuspell\structures.hxx(234): error C2091: function returns function
1>firstparser.cxx
1>Generating Code...
1>Done building project "Project1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

![image](https://user-images.githubusercontent.com/4847132/41832359-4f05c208-787e-11e8-9e3c-f025e725c48a.png)

**Comment by LiMinggang** [comment]
MSDN said

Compiler Error C2091
function returns function

A function cannot return a function. Return a pointer to a function instead.

**Comment by dimztimz** [comment]
We dobt support msvc builds right now. On windows use msys2+mingw-w64

**Comment by LiMinggang** [comment]
@PanderMusubi asked me to have a try. I thought it was a developer of nuspell. https://github.com/hunspell/hunspell/pull/574

**Comment by dimztimz** [comment]
Ok thanks, I'll try to fix some stuff but won't promise anything. MSVC support will be document only before final release. It will depend additionally on vcpkg to pull dependencies.

**Comment by PanderMusubi** [comment]
(was typing this before comment of d, and yes I'm also doing development for nuspell)

Thanks for this test. Which version of Boost did yo use?

Could you retest with:
* latest stable Boost version, minimally version 1.62
* with the latest commit, Hunzip will not be supported so I have disabled that part. The code is only temporarily included in Nuspell.
* with `-Wno-unknown-pragmas` added to the project/build file to get rid of the warnings or the GCC specific pragmas could be disabled with an `#ifdef` macro excluding it for all non-GCC platforms.
* if you have a suggestion how to solve the "function returns function", please let us know

(@dimztimz I asked @LiMinggang to do a test, simply to see how well it ports as is and get some early adapters familiar with Nuspell.)

**Comment by LiMinggang** [comment]
I'm using boost 1.66.0.
The error goes away after using ifdef. Another error blocks the compiling now

1>c:\dev\nuspell-master\src\nuspell\dictionary.hxx(287): note: see reference to function template instantiation 'nuspell::Spell_Result nuspell::Dictionary::spell_priv<char>(std::basic_string<char,std::char_traits<char>,std::allocator<char>>)' being compiled
1>c:\dev\nuspell-master\src\nuspell\dictionary.cxx(297): warning C4309: 'static_cast': truncation of constant value
1>c:\dev\nuspell-master\src\nuspell\dictionary.cxx(224): note: see reference to function template instantiation 'const nuspell::Flag_Set *nuspell::Dictionary::spell_sharps<char>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &,size_t,size_t,size_t)' being compiled
1>c:\dev\nuspell-master\src\nuspell\dictionary.cxx(176): note: see reference to function template instantiation 'const nuspell::Flag_Set *nuspell::Dictionary::spell_casing_upper<char>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)' being compiled
1>locale_utils.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
**1>c:\dev\nuspell-master\src\nuspell\locale_utils.cxx(31): fatal error C1083: Cannot open include file: 'unicode/uchar.h': No such file or directory**
1>main.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>structures.cxx
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>Generating Code...
1>Done building project "Project1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

#include <unicode/uchar.h>
#include <unicode/ucnv.h>
#include <unicode/unistr.h>

**Comment by LiMinggang** [comment]
I've no idea how to fix the "function returns function" issue. It seemed that MSVC don't support the C++ feature used----MS does not support all features in the standard.

You might fix is by it suggested, aka, return function point instead of a function object.

**Comment by PanderMusubi** [comment]
Thanks again, also for the suggestion. Boost is new enough. On Ubuntu, that `uchar.h` is found in package `libicu-dev`, Development files for International Components for Unicode.

But as Dimitrij says, for now we are not actively supporting it now, also code can still change a lot, but feel free to see if you get it building or not.

**Comment by dimztimz** [comment]
With the latest commit hopefully there should be no compile errors under MSVC. We advise you to use the very latest 2017 version of MSVC as the code uses many c++14 features.
Additionally I advise you to use [vcpkg](https://docs.microsoft.com/en-us/cpp/vcpkg) ([link2](https://github.com/Microsoft/vcpkg)) to pull the dependencies, boost with boost locale and ICU, before compiling.

Please test and close this if everything is successful.
