### ISSUE TITLE
What is the difference between Nuspell and Hunspell?

### ISSUE THREAD

**Issue by nadavb** [hunspell/nuspell#4]
What is the difference between Nuspell and Hunspell?

**Comment by PanderMusubi** [comment]
Nuspell is a pure C++ reimplementation of Hunspell which will be better maintainable and extendable. Eventually it will replace Hunspell. The first goal is to make it an in-place replacement for usage by web browsers and office suites. Would like to be involved or help out?

**Comment by nadavb** [comment]
Thanks. When you say that "Nuspell is a pure C++ reimplementation", does it mean that Hunspell is not written in C++? What is Hunspell written in then? C?

I am learning the technologies, and when I'll be ready will be happy to contribute, but probably will take some time ;)

**Comment by PanderMusubi** [comment]
It was started in C but then got upgraded to C++. In the beginning there wasn't that much support for templates, locales, etc. So it has a lot of C-style solutions which are very elaborate and hard to maintain.

If you need help understanding the format of the affix and dict file let us know. We can also use a hand with community building and a new but simple website.
