### ISSUE TITLE
Nu suggestions on command line

### ISSUE THREAD

**Issue by baarsrj** [hunspell/nuspell#9]
The issues can be of three types (put an X between the brackets):

- [ x] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = | Kubuntu 16      |
| Hunspell version                = |   nuspell    |
| Dictionary,package name,version = |       |
| Command line tool or GUI app    = |   cmdline    |

## Steps to reproduce
start Nuspell, settings to Dutch.

## Bugged behavior (output)
ruud@ruud-laptop:~/Bureaublad/nuspell-master$ nuspell 
INFO: Input  locale name=nl_NL.UTF-8, lang=nl, country=NL, enc=utf-8
INFO: Output locale name=nl_NL.UTF-8, lang=nl, country=NL, enc=utf-8
INFO: Pointed dictionary /usr/share/hunspell/nl_NL.{dic,aff}
duer
&
deur
*

## Expected behaviour (output)
Expected primitive user interface to deal and suggestions.

# Change/feature request

If you want current behavior to get changed, please explain how do you
want it changed. If it's completely new, please explain it how do you
want it, as verbose as possible.

# Other issues

If you have just questions or some other type of issue, you have the
freedom to ask it in any way. Try to be as verbose as possible.

**Comment by dimztimz** [comment]
As stated in the readme this product is still under development and suggestions are not implemented. Come back in few months and they will be here :) .

**Comment by baarsrj** [comment]
Okay, I understand. Where can I find the 'to be implemented yet' list?

**Comment by nikita-moor** [comment]
@baarsrj development roadmap is [here](https://github.com/hunspell/hunspell/wiki/Version-2-Specification).
